define({
    TILE_SIZE: 16,
    LINE_HEIGHT: 16,
    GAME_WIDTH: 320,
    GAME_HEIGHT: 240,
    DEFAULT_SCALE: 1,
    WINDOW_IB_COLOR: "#025",
    WINDOW_OB_COLOR: "#ddd",
    WINDOW_BG_COLOR: "#025",
    DEAD_WINDOW_BG_COLOR: "#520",
    HILIGHT_WINDOW_BG_COLOR: "#136",
    WINDOW_TEXT_COLOR: "#fff",
    FACE_WIDTH: 48,
    FACE_HEIGHT: 48,
    STATUS_WINDOW_WIDTH: 36,
    STATUS_WINDOW_HEIGHT: 44,
    ACTOR_WIDTH: 16,
    ACTOR_HEIGHT: 18,
    ACTOR_HEAD: 4,
    chars: {
        HEART: "&",
        STAR: "<",
        POINTER: ">"
    }
});